name: Receive and push
on: push

jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File

        steps:
        - name: Checkout Project A
          uses: actions/checkout@v2
          with:
            path: ./testRepo1

        - name: Checkout Project B
          uses: actions/checkout@master
          with: 
            repository: Brancieq-Paul/testRepo2
            token: ${{ secrets.API_TOKEN_GITHUB }}
            path: ./testRepo2

        - name: Copy/Create file
          run: |
            cp -r ./testRepo1/*.txt ./testRepo2/

        - name: Push Project B
          run: |
            cd ./testRepo2
            git add .
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -am "File Replicated from Project A"
            git push